export interface Country {
  name: string;
  code: string;
  phoneLengths: number[]; 
}

export const countries: Country[] = [
  { name: 'Afghanistan', code: '+93', phoneLengths: [9] },
  { name: 'Albania', code: '+355', phoneLengths: [8,9] },
  { name: 'Algeria', code: '+213', phoneLengths: [9] },
  { name: 'Andorra', code: '+376', phoneLengths: [6] },
  { name: 'Angola', code: '+244', phoneLengths: [9] },
  { name: 'Argentina', code: '+54', phoneLengths: [10] },
  { name: 'Armenia', code: '+374', phoneLengths: [8] },
  { name: 'Australia', code: '+61', phoneLengths: [9] },
  { name: 'Austria', code: '+43', phoneLengths: [10] },
  { name: 'Azerbaijan', code: '+994', phoneLengths: [9] },
  { name: 'Bahamas', code: '+1', phoneLengths: [10] },
  { name: 'Bahrain', code: '+973', phoneLengths: [8] },
  { name: 'Bangladesh', code: '+880', phoneLengths: [10] },
  { name: 'Belarus', code: '+375', phoneLengths: [9] },
  { name: 'Belgium', code: '+32', phoneLengths: [9] },
  { name: 'Belize', code: '+501', phoneLengths: [7] },
  { name: 'Benin', code: '+229', phoneLengths: [8] },
  { name: 'Bhutan', code: '+975', phoneLengths: [8] },
  { name: 'Bolivia', code: '+591', phoneLengths: [8] },
  { name: 'Bosnia and Herzegovina', code: '+387', phoneLengths: [8,9] },
  { name: 'Botswana', code: '+267', phoneLengths: [7] },
  { name: 'Brazil', code: '+55', phoneLengths: [10,11] },
  { name: 'Brunei', code: '+673', phoneLengths: [7] },
  { name: 'Bulgaria', code: '+359', phoneLengths: [9] },
  { name: 'Burkina Faso', code: '+226', phoneLengths: [8] },
  { name: 'Burundi', code: '+257', phoneLengths: [8] },
  { name: 'Cambodia', code: '+855', phoneLengths: [8,9] },
  { name: 'Cameroon', code: '+237', phoneLengths: [9] },
  { name: 'Canada', code: '+1', phoneLengths: [10] },
  { name: 'Cape Verde', code: '+238', phoneLengths: [7] },
  { name: 'Central African Republic', code: '+236', phoneLengths: [8] },
  { name: 'Chad', code: '+235', phoneLengths: [8] },
  { name: 'Chile', code: '+56', phoneLengths: [9] },
  { name: 'China', code: '+86', phoneLengths: [11] },
  { name: 'Colombia', code: '+57', phoneLengths: [10] },
  { name: 'Comoros', code: '+269', phoneLengths: [7] },
  { name: 'Congo', code: '+242', phoneLengths: [9] },
  { name: 'Costa Rica', code: '+506', phoneLengths: [8] },
  { name: 'Croatia', code: '+385', phoneLengths: [9] },
  { name: 'Cuba', code: '+53', phoneLengths: [8] },
  { name: 'Cyprus', code: '+357', phoneLengths: [8] },
  { name: 'Czech Republic', code: '+420', phoneLengths: [9] },
  { name: 'Denmark', code: '+45', phoneLengths: [8] },
  { name: 'Djibouti', code: '+253', phoneLengths: [8] },
  { name: 'Dominica', code: '+1', phoneLengths: [10] },
  { name: 'Dominican Republic', code: '+1', phoneLengths: [10] },
  { name: 'Ecuador', code: '+593', phoneLengths: [9] },
  { name: 'Egypt', code: '+20', phoneLengths: [10] },
  { name: 'El Salvador', code: '+503', phoneLengths: [8] },
  { name: 'Equatorial Guinea', code: '+240', phoneLengths: [9] },
  { name: 'Eritrea', code: '+291', phoneLengths: [7] },
  { name: 'Estonia', code: '+372', phoneLengths: [7,8] },
  { name: 'Eswatini', code: '+268', phoneLengths: [7] },
  { name: 'Ethiopia', code: '+251', phoneLengths: [9] },
  { name: 'Fiji', code: '+679', phoneLengths: [7] },
  { name: 'Finland', code: '+358', phoneLengths: [9] },
  { name: 'France', code: '+33', phoneLengths: [9,10] },
  { name: 'Gabon', code: '+241', phoneLengths: [7] },
  { name: 'Gambia', code: '+220', phoneLengths: [7] },
  { name: 'Georgia', code: '+995', phoneLengths: [9] },
  { name: 'Germany', code: '+49', phoneLengths: [10,11] },
  { name: 'Ghana', code: '+233', phoneLengths: [9] },
  { name: 'Greece', code: '+30', phoneLengths: [10] },
  { name: 'Guatemala', code: '+502', phoneLengths: [8] },
  { name: 'Guinea', code: '+224', phoneLengths: [8] },
  { name: 'Guinea-Bissau', code: '+245', phoneLengths: [7] },
  { name: 'Guyana', code: '+592', phoneLengths: [7] },
  { name: 'Haiti', code: '+509', phoneLengths: [8] },
  { name: 'Honduras', code: '+504', phoneLengths: [8] },
  { name: 'Hungary', code: '+36', phoneLengths: [9] },
  { name: 'Iceland', code: '+354', phoneLengths: [7] },
  { name: 'India', code: '+91', phoneLengths: [10] },
  { name: 'Indonesia', code: '+62', phoneLengths: [9,10,11] },
  { name: 'Iran', code: '+98', phoneLengths: [10] },
  { name: 'Iraq', code: '+964', phoneLengths: [10] },
  { name: 'Ireland', code: '+353', phoneLengths: [9] },
  { name: 'Israel', code: '+972', phoneLengths: [9] },
  { name: 'Italy', code: '+39', phoneLengths: [9,10] },
  { name: 'Jamaica', code: '+1', phoneLengths: [10] },
  { name: 'Japan', code: '+81', phoneLengths: [10] },
  { name: 'Jordan', code: '+962', phoneLengths: [9] },
  { name: 'Kazakhstan', code: '+7', phoneLengths: [10] },
  { name: 'Kenya', code: '+254', phoneLengths: [9] },
  { name: 'Kiribati', code: '+686', phoneLengths: [5] },
  { name: 'Kuwait', code: '+965', phoneLengths: [8] },
  { name: 'Kyrgyzstan', code: '+996', phoneLengths: [9] },
  { name: 'Laos', code: '+856', phoneLengths: [8] },
  { name: 'Latvia', code: '+371', phoneLengths: [8] },
  { name: 'Lebanon', code: '+961', phoneLengths: [8] },
  { name: 'Lesotho', code: '+266', phoneLengths: [8] },
  { name: 'Liberia', code: '+231', phoneLengths: [7,8] },
  { name: 'Libya', code: '+218', phoneLengths: [9] },
  { name: 'Liechtenstein', code: '+423', phoneLengths: [7] },
  { name: 'Lithuania', code: '+370', phoneLengths: [8,9] },
  { name: 'Luxembourg', code: '+352', phoneLengths: [8,9] },
  { name: 'Madagascar', code: '+261', phoneLengths: [9] },
  { name: 'Malawi', code: '+265', phoneLengths: [9] },
  { name: 'Malaysia', code: '+60', phoneLengths: [9,10] },
  { name: 'Maldives', code: '+960', phoneLengths: [7] },
  { name: 'Mali', code: '+223', phoneLengths: [8] },
  { name: 'Malta', code: '+356', phoneLengths: [8] },
  { name: 'Marshall Islands', code: '+692', phoneLengths: [7] },
  { name: 'Mauritania', code: '+222', phoneLengths: [8] },
  { name: 'Mauritius', code: '+230', phoneLengths: [8,9] },
  { name: 'Mexico', code: '+52', phoneLengths: [10] },
  { name: 'Micronesia', code: '+691', phoneLengths: [7] },
  { name: 'Moldova', code: '+373', phoneLengths: [8] },
  { name: 'Monaco', code: '+377', phoneLengths: [8] },
  { name: 'Mongolia', code: '+976', phoneLengths: [8] },
  { name: 'Montenegro', code: '+382', phoneLengths: [8,9] },
  { name: 'Morocco', code: '+212', phoneLengths: [9] },
  { name: 'Mozambique', code: '+258', phoneLengths: [9] },
  { name: 'Myanmar', code: '+95', phoneLengths: [9] },
  { name: 'Namibia', code: '+264', phoneLengths: [9] },
  { name: 'Nauru', code: '+674', phoneLengths: [5] },
  { name: 'Nepal', code: '+977', phoneLengths: [10] },
  { name: 'Netherlands', code: '+31', phoneLengths: [9] },
  { name: 'New Zealand', code: '+64', phoneLengths: [9] },
  { name: 'Nicaragua', code: '+505', phoneLengths: [8] },
  { name: 'Niger', code: '+227', phoneLengths: [8] },
  { name: 'Nigeria', code: '+234', phoneLengths: [10] },
  { name: 'North Korea', code: '+850', phoneLengths: [8,9] },
  { name: 'Norway', code: '+47', phoneLengths: [8] },
  { name: 'Oman', code: '+968', phoneLengths: [8] },
  { name: 'Pakistan', code: '+92', phoneLengths: [10] },
  { name: 'Palau', code: '+680', phoneLengths: [7] },
  { name: 'Palestine', code: '+970', phoneLengths: [9] },
  { name: 'Panama', code: '+507', phoneLengths: [8] },
  { name: 'Papua New Guinea', code: '+675', phoneLengths: [7,8] },
  { name: 'Paraguay', code: '+595', phoneLengths: [9] },
  { name: 'Peru', code: '+51', phoneLengths: [9] },
  { name: 'Philippines', code: '+63', phoneLengths: [10] },
  { name: 'Poland', code: '+48', phoneLengths: [9] },
  { name: 'Portugal', code: '+351', phoneLengths: [9] },
  { name: 'Qatar', code: '+974', phoneLengths: [8] },
  { name: 'Romania', code: '+40', phoneLengths: [9] },
  { name: 'Russia', code: '+7', phoneLengths: [10] },
  { name: 'Rwanda', code: '+250', phoneLengths: [9] },
  { name: 'Saint Kitts and Nevis', code: '+1', phoneLengths: [10] },
  { name: 'Saint Lucia', code: '+1', phoneLengths: [10] },
  { name: 'Saint Vincent and the Grenadines', code: '+1', phoneLengths: [10] },
  { name: 'Samoa', code: '+685', phoneLengths: [7] },
  { name: 'San Marino', code: '+378', phoneLengths: [8,9] },
  { name: 'Saudi Arabia', code: '+966', phoneLengths: [9] },
  { name: 'Senegal', code: '+221', phoneLengths: [9] },
  { name: 'Serbia', code: '+381', phoneLengths: [8,9] },
  { name: 'Seychelles', code: '+248', phoneLengths: [7] },
  { name: 'Sierra Leone', code: '+232', phoneLengths: [8] },
  { name: 'Singapore', code: '+65', phoneLengths: [8] },
  { name: 'Slovakia', code: '+421', phoneLengths: [9] },
  { name: 'Slovenia', code: '+386', phoneLengths: [8,9] },
  { name: 'Solomon Islands', code: '+677', phoneLengths: [7] },
  { name: 'Somalia', code: '+252', phoneLengths: [8] },
  { name: 'South Africa', code: '+27', phoneLengths: [9] },
  { name: 'South Korea', code: '+82', phoneLengths: [10] },
  { name: 'Spain', code: '+34', phoneLengths: [9] },
  { name: 'Sri Lanka', code: '+94', phoneLengths: [9] },
  { name: 'Sudan', code: '+249', phoneLengths: [9] },
  { name: 'Suriname', code: '+597', phoneLengths: [7] },
  { name: 'Sweden', code: '+46', phoneLengths: [9] },
  { name: 'Switzerland', code: '+41', phoneLengths: [9] },
  { name: 'Syria', code: '+963', phoneLengths: [9] },
  { name: 'Taiwan', code: '+886', phoneLengths: [9] },
  { name: 'Tajikistan', code: '+992', phoneLengths: [9] },
  { name: 'Tanzania', code: '+255', phoneLengths: [9] },
  { name: 'Thailand', code: '+66', phoneLengths: [9] },
  { name: 'Togo', code: '+228', phoneLengths: [8] },
  { name: 'Tonga', code: '+676', phoneLengths: [6,7] },
  { name: 'Trinidad and Tobago', code: '+1', phoneLengths: [10] },
  { name: 'Tunisia', code: '+216', phoneLengths: [8] },
  { name: 'Turkey', code: '+90', phoneLengths: [10] },
  { name: 'Turkmenistan', code: '+993', phoneLengths: [8] },
  { name: 'Tuvalu', code: '+688', phoneLengths: [5,6] },
  { name: 'Uganda', code: '+256', phoneLengths: [9] },
  { name: 'Ukraine', code: '+380', phoneLengths: [9] },
  { name: 'United Arab Emirates', code: '+971', phoneLengths: [9] },
  { name: 'United Kingdom', code: '+44', phoneLengths: [10] },
  { name: 'United States', code: '+1', phoneLengths: [10] },
  { name: 'Uruguay', code: '+598', phoneLengths: [8,9] },
  { name: 'Uzbekistan', code: '+998', phoneLengths: [9] },
  { name: 'Vanuatu', code: '+678', phoneLengths: [7] },
  { name: 'Vatican', code: '+379', phoneLengths: [9] },
  { name: 'Venezuela', code: '+58', phoneLengths: [10] },
  { name: 'Vietnam', code: '+84', phoneLengths: [9,10] },
  { name: 'Yemen', code: '+967', phoneLengths: [9] },
  { name: 'Zambia', code: '+260', phoneLengths: [9] },
  { name: 'Zimbabwe', code: '+263', phoneLengths: [9] },
];